name: run module 

on:
  schedule:
    - cron: '45 12 * * *' #0700 local time, 1245 utc
    - cron: '15 16 * * *' #1030 local time, 1615 utc
    - cron: '30 16 * * *' #1045 local time, 1630 utc
    - cron: '45 20 * * *' #1500 local time, 2015 utc

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8' 
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r Requirements.txt
          
      - name: execute module 
        run: python -m nepse